# Generated by Django 2.2.1 on 2019-05-29 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('birthday', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('area', models.TextField()),
                ('knowledges', models.TextField()),
                ('opendoors', models.BooleanField()),
            ],
        ),
    ]
